baseURL = 'http://asonestrategy.com/'
languageCode = 'en-us'
title = 'As One Strategy'
theme = []
relativeURLs = true

[params]
  description = "Together We Thrive"
  author = "Hannah Lorenzo"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "#about"
    weight = 10
  [[menu.main]]
    identifier = "speaking"
    name = "Speaking"
    url = "#speaking"
    weight = 20
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "#books"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "#contact"
    weight = 40
